# -*- coding: utf-8 -*-
"""exercise 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IDBhv3N4UB8bM-QFxSCuk9qUXFNFd1hC
"""

!pip install wordcloud

from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

# Open and read the text file
with open('/content/JaneEyre.txt', 'r') as file:
    text = file.read()

from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

# Generate the word cloud
wordcloud = WordCloud(
    width=800,
    height=400,
    background_color="white",
    stopwords=set(STOPWORDS),
    min_font_size=10
).generate(text)

# Display the word cloud
plt.figure(figsize=(8, 8), facecolor=None)
plt.imshow(wordcloud)
plt.axis("off")
plt.tight_layout(pad=0)
plt.show()

!pip install wordcloud pillow

from PIL import Image
import numpy as np

# Load the mask image and convert it to a NumPy array
mask = np.array(Image.open('/content/mask_image.jpg'))

from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

# Create the WordCloud object with the mask
wordcloud = WordCloud(
    width=800,
    height=400,
    background_color="white",
    stopwords=set(STOPWORDS),
    mask=mask,  # Apply the mask here
    contour_width=1,
    contour_color='black'
).generate(text)

# Display the word cloud
plt.figure(figsize=(10, 10), facecolor=None)
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.tight_layout(pad=0)
plt.show()

from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

from PIL import Image
import numpy as np

# Load the mask image and convert it to a NumPy array
mask = np.array(Image.open('/content/mask_image12.jpeg'))
# Create the WordCloud object with the mask
wordcloud = WordCloud(
    width=800,
    height=400,
    background_color="black",
    stopwords=set(STOPWORDS),
    mask=mask,  # Apply the mask here
    contour_width=1,
    contour_color='yellow'
).generate(text)

# Display the word cloud
plt.figure(figsize=(10, 10), facecolor=None)
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.tight_layout(pad=0)
plt.show()

from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

from PIL import Image
import numpy as np

# Load the mask image and convert it to a NumPy array
mask = np.array(Image.open('/content/mask_image10.jpeg'))
# Create the WordCloud object with the mask
wordcloud = WordCloud(
    width=800,
    height=400,
    background_color="pink",
    stopwords=set(STOPWORDS),
    mask=mask,  # Apply the mask here
    contour_width=1,
    contour_color='black'
).generate(text)

# Display the word cloud
plt.figure(figsize=(10, 10), facecolor=None)
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.tight_layout(pad=0)
plt.show()

from wordcloud import WordCloud, STOPWORDS
import matplotlib.pyplot as plt

from PIL import Image
import numpy as np

# Load the mask image and convert it to a NumPy array
mask = np.array(Image.open('/content/mask_image5.jpeg'))
wordcloud = WordCloud(
    width=800,
    height=400,
    background_color="black",
    colormap="plasma",
    max_words=300,
    stopwords=set(STOPWORDS),
    mask=mask,
    contour_width=1,
    contour_color='purple'
).generate(text)

# Display the word cloud
plt.figure(figsize=(10, 10), facecolor=None)
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.tight_layout(pad=0)
plt.show()